version: '3.8'

services:
  goapp:
    build: .
    container_name: goapp
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: air run main.go
  pgsql:
    image: postgres:alpine
    container_name: pgsql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_port=${DB_PORT}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: